In [1]:
# Support vector machine --- supervised learning algorithm
# Regression & Classification (primarily used for classification)

# What is all about support vector?

In [2]:
# We will try to create a LINE / HYPERPLANE in n-dimension so that it maximizes the distance 
#between the hyperplane and the closest points. This distance is known margin.
#So SVM is basically a margin maximization algorithm
#The closest points that reside on the margin are called support vectors. 

In [3]:
# What SVM does is in case of non - linear relationship --- it transforms the data to higher
#dimension to find out a linear hyperplane that linearly separates the classes.
# this is known as kernel trick.

# So, SVM uses linear classifier to classify non linera relationship.
    

In [4]:
# Transformation of the data to higher dimension is done by using few functions - 

In [5]:
# 3 main hyperparameter --- 
# What kernel to use for transaformation - LINEAR FUNCTION, POLYNOMIAL, RBF
# If you choose polynomial what order of polynomial do you want to use?
# Penalty parameter makes SUpport vector machine forget outlier values in 
# the margin area.If the penalty parameter is High, then overfitting is high...i.e SVM cannot forget
#the outlier values in building the margin.
#Wherease if C value is low , that means the algorithm has forgotten and my model is less pverfit

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
iris_Data = load_iris()

In [71]:
indep_var = pd.DataFrame(iris_Data['data'],columns=iris_Data.feature_names)

In [73]:
dep_var = pd.DataFrame(iris_Data['target'],columns=['FlowerType'])

In [74]:
full_Data = pd.concat([indep_var,dep_var],axis=1)

In [75]:
X = full_Data.drop('FlowerType',axis=1)
Y = full_Data['FlowerType']

In [78]:
full_Data['FlowerType'].unique()

array([0, 1, 2], dtype=int64)

In [80]:
from sklearn import svm
svc_mod = svm.SVC() # C parameter controls overfitting --- regularization parameter

In [ ]:
# The C parameter tells SVM how much you want to avoid the misclassification
#for large values of C --- means you are telling the algorithm u cannot afford misclassification ... u r okay to have narro margin
#For small values of C ---- you can afford to have miscalssification for the sake of wider margin

In [81]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,random_state = 42)

In [85]:
from sklearn.model_selection import GridSearchCV
parameters_svm = {'C':[0.001,0.01,0.1,0.5,1],
                 'kernel':['rbf','linear']
                 }
gridsearch_svm = GridSearchCV(svc_mod,cv=5,param_grid=parameters_svm,scoring='balanced_accuracy')

In [86]:
gridsearch_svm.fit(X_train,Y_train)

C:\Users\Admin\Anaconda2\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Admin\Anaconda2\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Admin\Anaconda2\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Admin\Anaconda2\lib\site-packages\sklearn\svm\base.py:196: FutureWarni

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'C': [0.001, 0.01, 0.1, 0.5, 1], 'kernel': ['rbf', 'linear']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='balanced_accuracy', verbose=0)

In [87]:
gridsearch_svm.best_params_

{'C': 0.5, 'kernel': 'linear'}

In [88]:
svc_mod2 = svm.SVC(C=0.5,kernel='linear')
svc_mod2.fit(X_train,Y_train)

SVC(C=0.5, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [89]:
Y_pred_test = svc_mod2.predict(X_test)

In [91]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test,Y_pred_test)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)

In [92]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred_test)


1.0

In [ ]:
### Neural Network --- WHEN YOUR TRAINING DATA IS HUGE IN SIZE
### XGBOOST --------------WHen you have good amount training data
### SVM ---------------- Is the 3rd best --- it works best if datapoints are less 

In [53]:
demo = pd.DataFrame({'Age':[18,20,25,30,40,45],
                    'Buy':[0,0,1,1,0,0]})

In [54]:
X = demo[['Age']]
Y = demo['Buy']

In [66]:
from sklearn import svm
svc_model = svm.SVC(kernel = 'rbf')
svc_model.fit(X,Y)

C:\Users\Admin\Anaconda2\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [67]:
svc_model.predict(X)

array([0, 0, 1, 1, 0, 0], dtype=int64)

In [ ]:
# APART FROM SVM NO OTHER LINEAR MODEL CAN HANDLE NON LINEAR DATA 
# GOOD THING ABOUT SVM IS TWO FOLD - 
# IT HAS VERY LOW VARIANCE
# for new data prediction it only cares about support vectors

In [ ]:
### SVM, NB can u do text classification


In [94]:
### Any text classification problem that we deal with will have following strcuture
# Any high level idea on how to handle text data



In [1]:
import os
file_path = r'C:\Users\Admin\Desktop\Edvancer\PythonClass\Data\Reuters Data'

In [2]:
all_files = os.listdir(file_path)

In [3]:
len(all_files)

928

In [4]:
all_text_files = []
for files in all_files:
    if '.txt' in files:
        all_text_files.append(files)

In [11]:
label = []
text = []
for f in all_text_files:
    filename = str(f)
    complete_text = []
    file_pointer = open(file_path+"\\"+ f)
    for l in file_pointer.readlines():
        complete_text.append(l.strip())
        #print(complete_text)
    
    text.append(complete_text[0])   
    return_crude = filename.find('crude')
    #print(return_crude)
    if (return_crude == -1):
        label.append('money_fx')
    else:
        label.append('crude')
        

In [12]:
len(text)

927

In [13]:
len(label)

927

In [14]:
import pandas as pd
text_df = pd.DataFrame({'label':label,
             'text':text})
text_df.head()

label                                               text
0  crude             CANADA OIL EXPORTS RISE 20 PCT IN 1986
1  crude  BP &lt;BP> DOES NOT PLAN TO HIKE STANDARD &lt;...
2  crude  BP&lt;BP> OFFER RAISES EXPECTATIONS FOR OIL VA...
3  crude  USX &lt;X> SAYS TALKS ENDED WITH BRITISH PETRO...
4  crude       BP &lt;BP> MAY HAVE TO RAISE BID -  ANALYSTS

In [15]:
text_df['label'].value_counts()

money_fx    538
crude       389
Name: label, dtype: int64

In [16]:
Y = (text_df['label'] == 'crude').astype(int)

In [17]:
####X = ...
### wewill need to split each of the sentences into words

### TOKENIZATION --- WORDS ARE TOKEN IN A SENTENCE
### We will convert each of the words to its numeric equivalent --- TFIDF
### Then we will be able to do modelling

In [265]:
text_df.to_csv("REUTERS_final_data.csv",index=False)

In [18]:
text_df.head()

label                                               text
0  crude             CANADA OIL EXPORTS RISE 20 PCT IN 1986
1  crude  BP &lt;BP> DOES NOT PLAN TO HIKE STANDARD &lt;...
2  crude  BP&lt;BP> OFFER RAISES EXPECTATIONS FOR OIL VA...
3  crude  USX &lt;X> SAYS TALKS ENDED WITH BRITISH PETRO...
4  crude       BP &lt;BP> MAY HAVE TO RAISE BID -  ANALYSTS

In [227]:
fp = open(r'C:\Users\Admin\Desktop\Edvancer\PythonClass\Data\Reuters Data\training_money-fx_1983.txt')

In [228]:
text = []
for l in fp:
    if l.strip()!="":
        print("".join(l.strip()))


EGYPTIAN CENTRAL BANK DOLLAR RATE UNCHANGED
Egypt's Central Bank today set the dollar
rate for commercial banks for March 6 at 1.373/87 dollars,
unchanged from the previous rate.
